name: Selenium Tests

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Conda setup
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true

    - name: Conda environment creation
      shell: bash -l {0}
      run: |
        conda create --yes --name TEST python=3 pip --file requirements.txt --file requirements-dev.txt --channel conda-forge --strict-channel-priority
        source activate TEST
        pip install -e . --no-deps --force-reinstall

    - name: Selenium tests
      shell: bash -l {0}
      run: |
        source activate TEST
        pytest tests/selenium -vv
